//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flores_De_Mayo_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alayan
    {
        public int AlaId { get; set; }
        public int SinId { get; set; }
        public int DSetIdApplied { get; set; }
        public int ATypId { get; set; }
        public int ADatId { get; set; }
        public string Remarks { get; set; }
        public string Reference { get; set; }
    
        public virtual AlayanDate AlayanDate { get; set; }
        public virtual AlayanType AlayanType { get; set; }
        public virtual DateSetting DateSetting { get; set; }
        public virtual SinisianDatabase SinisianDatabase { get; set; }
    }
}
