//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flores_De_Mayo_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.SagalaPartners = new HashSet<SagalaPartner>();
            this.SagalaPartners1 = new HashSet<SagalaPartner>();
        }
    
        public int AppId { get; set; }
        public int ASTypId { get; set; }
        public int ATypeId { get; set; }
        public int SinId { get; set; }
        public int DSetIdApplied { get; set; }
        public Nullable<int> DSetIdEvaluated { get; set; }
        public string UserIdEvaluated { get; set; }
        public string Remarks { get; set; }
        public string RerenceNum { get; set; }
    
        public virtual ApplicationStatusType ApplicationStatusType { get; set; }
        public virtual ApplicationType ApplicationType { get; set; }
        public virtual DateSetting DateSetting { get; set; }
        public virtual DateSetting DateSetting1 { get; set; }
        public virtual SinisianDatabase SinisianDatabase { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SagalaPartner> SagalaPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SagalaPartner> SagalaPartners1 { get; set; }
    }
}
