//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flores_De_Mayo_Information_System.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Alayan> Alayans { get; set; }
        public virtual DbSet<AlayanDate> AlayanDates { get; set; }
        public virtual DbSet<AlayanDateType> AlayanDateTypes { get; set; }
        public virtual DbSet<AlayanType> AlayanTypes { get; set; }
        public virtual DbSet<AnnouncementAsset> AnnouncementAssets { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationStatusType> ApplicationStatusTypes { get; set; }
        public virtual DbSet<ApplicationType> ApplicationTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DateSetting> DateSettings { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FileStorage> FileStorages { get; set; }
        public virtual DbSet<OfficerHierarchy> OfficerHierarchies { get; set; }
        public virtual DbSet<OfficerPartner> OfficerPartners { get; set; }
        public virtual DbSet<SagalaPartner> SagalaPartners { get; set; }
        public virtual DbSet<SagalaTitle> SagalaTitles { get; set; }
        public virtual DbSet<SinisianDatabase> SinisianDatabases { get; set; }
        public virtual DbSet<WebSetting> WebSettings { get; set; }
    }
}
