//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flores_De_Mayo_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerHierarchy
    {
        public int OHieId { get; set; }
        public int OParId { get; set; }
        public int Rank { get; set; }
    
        public virtual OfficerPartner OfficerPartner { get; set; }
    }
}
