//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flores_De_Mayo_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerPartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfficerPartner()
        {
            this.OfficerHierarchies = new HashSet<OfficerHierarchy>();
        }
    
        public int OParId { get; set; }
        public string UserIdMale { get; set; }
        public string UserIdFemale { get; set; }
        public Nullable<bool> IsPresident { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficerHierarchy> OfficerHierarchies { get; set; }
    }
}
