//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flores_De_Mayo_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SagalaPartner
    {
        public int SParId { get; set; }
        public int AppIdFirst { get; set; }
        public Nullable<int> AppIdSec { get; set; }
        public int STitId { get; set; }
        public int DSetId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Application Application1 { get; set; }
        public virtual DateSetting DateSetting { get; set; }
        public virtual SagalaTitle SagalaTitle { get; set; }
    }
}
