//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flores_De_Mayo_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSetting
    {
        public int WSetId { get; set; }
        public int DSetId { get; set; }
        public bool ApplicationOpen { get; set; }
    
        public virtual DateSetting DateSetting { get; set; }
    }
}
